version: '3.5'
services:
    eth1:
        image: ethereum/client-go:latest
        container_name: eth1
        restart: always
        volumes:
            - ./private/eth1_node:/root
        network_mode: host
        command: 
            - --goerli


    postgres:
        image: postgres:12.0
        container_name: postgres 
        restart: always
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=postgres
            - POSTGRES_DB=db
            - PGDATA=/postgresql/data
        volumes:
            - db:/postgresql/data
        network_mode: host

    prysm:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
        container_name: prysm 
        restart: always
        volumes:
            - ./private/eth2_data:/data
            - ./private/eth1_node/.ethereum/goerli:$HOME/Goerli
        network_mode: host
        command: 
            - --datadir=/data
            - --rpc-host=0.0.0.0
            - --monitoring-host=0.0.0.0
            - --http-web3provider=$HOME/Goerli/geth.ipc
            - --accept-terms-of-use
        depends_on:
            - eth1

    go:
        image: golang:1.14
        container_name: golang 
        restart: always
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        network_mode: host
        depends_on:
            - eth1
            - postgres
            - prysm
        command: /bin/sh
        stdin_open: true
        tty: true

volumes: 
    db: