// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: ens.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsNameRegistered struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParentHash       []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber      uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	RegisterContract []byte                 `protobuf:"bytes,3,opt,name=register_contract,json=registerContract,proto3" json:"register_contract,omitempty"`
	ResolverContract []byte                 `protobuf:"bytes,4,opt,name=resolver_contract,json=resolverContract,proto3" json:"resolver_contract,omitempty"`
	Time             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Label            []byte                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Owner            []byte                 `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Resolver         []byte                 `protobuf:"bytes,8,opt,name=resolver,proto3" json:"resolver,omitempty"`
	Node             []byte                 `protobuf:"bytes,9,opt,name=node,proto3" json:"node,omitempty"`
	Name             []byte                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Expires          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnsNameRegistered) Reset() {
	*x = EnsNameRegistered{}
	mi := &file_ens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsNameRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsNameRegistered) ProtoMessage() {}

func (x *EnsNameRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_ens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsNameRegistered.ProtoReflect.Descriptor instead.
func (*EnsNameRegistered) Descriptor() ([]byte, []int) {
	return file_ens_proto_rawDescGZIP(), []int{0}
}

func (x *EnsNameRegistered) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *EnsNameRegistered) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *EnsNameRegistered) GetRegisterContract() []byte {
	if x != nil {
		return x.RegisterContract
	}
	return nil
}

func (x *EnsNameRegistered) GetResolverContract() []byte {
	if x != nil {
		return x.ResolverContract
	}
	return nil
}

func (x *EnsNameRegistered) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EnsNameRegistered) GetLabel() []byte {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *EnsNameRegistered) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *EnsNameRegistered) GetResolver() []byte {
	if x != nil {
		return x.Resolver
	}
	return nil
}

func (x *EnsNameRegistered) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *EnsNameRegistered) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *EnsNameRegistered) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

type EnsNameRenewed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Label         []byte                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Name          []byte                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Expires       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsNameRenewed) Reset() {
	*x = EnsNameRenewed{}
	mi := &file_ens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsNameRenewed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsNameRenewed) ProtoMessage() {}

func (x *EnsNameRenewed) ProtoReflect() protoreflect.Message {
	mi := &file_ens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsNameRenewed.ProtoReflect.Descriptor instead.
func (*EnsNameRenewed) Descriptor() ([]byte, []int) {
	return file_ens_proto_rawDescGZIP(), []int{1}
}

func (x *EnsNameRenewed) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *EnsNameRenewed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *EnsNameRenewed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EnsNameRenewed) GetLabel() []byte {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *EnsNameRenewed) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *EnsNameRenewed) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

type EnsAddressChanged struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentHash      []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ResolveContract []byte                 `protobuf:"bytes,3,opt,name=resolve_contract,json=resolveContract,proto3" json:"resolve_contract,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Node            []byte                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	CoinType        uint64                 `protobuf:"varint,6,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	NewAddress      []byte                 `protobuf:"bytes,7,opt,name=new_address,json=newAddress,proto3" json:"new_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnsAddressChanged) Reset() {
	*x = EnsAddressChanged{}
	mi := &file_ens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsAddressChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsAddressChanged) ProtoMessage() {}

func (x *EnsAddressChanged) ProtoReflect() protoreflect.Message {
	mi := &file_ens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsAddressChanged.ProtoReflect.Descriptor instead.
func (*EnsAddressChanged) Descriptor() ([]byte, []int) {
	return file_ens_proto_rawDescGZIP(), []int{2}
}

func (x *EnsAddressChanged) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *EnsAddressChanged) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *EnsAddressChanged) GetResolveContract() []byte {
	if x != nil {
		return x.ResolveContract
	}
	return nil
}

func (x *EnsAddressChanged) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EnsAddressChanged) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *EnsAddressChanged) GetCoinType() uint64 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *EnsAddressChanged) GetNewAddress() []byte {
	if x != nil {
		return x.NewAddress
	}
	return nil
}

type EnsNameChanged struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentHash      []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ResolveContract []byte                 `protobuf:"bytes,3,opt,name=resolve_contract,json=resolveContract,proto3" json:"resolve_contract,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Node            []byte                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	NewName         []byte                 `protobuf:"bytes,6,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnsNameChanged) Reset() {
	*x = EnsNameChanged{}
	mi := &file_ens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsNameChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsNameChanged) ProtoMessage() {}

func (x *EnsNameChanged) ProtoReflect() protoreflect.Message {
	mi := &file_ens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsNameChanged.ProtoReflect.Descriptor instead.
func (*EnsNameChanged) Descriptor() ([]byte, []int) {
	return file_ens_proto_rawDescGZIP(), []int{3}
}

func (x *EnsNameChanged) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *EnsNameChanged) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *EnsNameChanged) GetResolveContract() []byte {
	if x != nil {
		return x.ResolveContract
	}
	return nil
}

func (x *EnsNameChanged) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EnsNameChanged) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *EnsNameChanged) GetNewName() []byte {
	if x != nil {
		return x.NewName
	}
	return nil
}

var File_ens_proto protoreflect.FileDescriptor

const file_ens_proto_rawDesc = "" +
	"\n" +
	"\tens.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x03\n" +
	"\x11EnsNameRegistered\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12+\n" +
	"\x11register_contract\x18\x03 \x01(\fR\x10registerContract\x12+\n" +
	"\x11resolver_contract\x18\x04 \x01(\fR\x10resolverContract\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05label\x18\x06 \x01(\fR\x05label\x12\x14\n" +
	"\x05owner\x18\a \x01(\fR\x05owner\x12\x1a\n" +
	"\bresolver\x18\b \x01(\fR\bresolver\x12\x12\n" +
	"\x04node\x18\t \x01(\fR\x04node\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\fR\x04name\x124\n" +
	"\aexpires\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"\xe4\x01\n" +
	"\x0eEnsNameRenewed\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05label\x18\x04 \x01(\fR\x05label\x12\x12\n" +
	"\x04name\x18\x05 \x01(\fR\x04name\x124\n" +
	"\aexpires\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"\x84\x02\n" +
	"\x11EnsAddressChanged\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12)\n" +
	"\x10resolve_contract\x18\x03 \x01(\fR\x0fresolveContract\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04node\x18\x05 \x01(\fR\x04node\x12\x1b\n" +
	"\tcoin_type\x18\x06 \x01(\x04R\bcoinType\x12\x1f\n" +
	"\vnew_address\x18\a \x01(\fR\n" +
	"newAddress\"\xde\x01\n" +
	"\x0eEnsNameChanged\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12)\n" +
	"\x10resolve_contract\x18\x03 \x01(\fR\x0fresolveContract\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04node\x18\x05 \x01(\fR\x04node\x12\x19\n" +
	"\bnew_name\x18\x06 \x01(\fR\anewNameB\tZ\a./typesb\x06proto3"

var (
	file_ens_proto_rawDescOnce sync.Once
	file_ens_proto_rawDescData []byte
)

func file_ens_proto_rawDescGZIP() []byte {
	file_ens_proto_rawDescOnce.Do(func() {
		file_ens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ens_proto_rawDesc), len(file_ens_proto_rawDesc)))
	})
	return file_ens_proto_rawDescData
}

var file_ens_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ens_proto_goTypes = []any{
	(*EnsNameRegistered)(nil),     // 0: types.EnsNameRegistered
	(*EnsNameRenewed)(nil),        // 1: types.EnsNameRenewed
	(*EnsAddressChanged)(nil),     // 2: types.EnsAddressChanged
	(*EnsNameChanged)(nil),        // 3: types.EnsNameChanged
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_ens_proto_depIdxs = []int32{
	4, // 0: types.EnsNameRegistered.time:type_name -> google.protobuf.Timestamp
	4, // 1: types.EnsNameRegistered.expires:type_name -> google.protobuf.Timestamp
	4, // 2: types.EnsNameRenewed.time:type_name -> google.protobuf.Timestamp
	4, // 3: types.EnsNameRenewed.expires:type_name -> google.protobuf.Timestamp
	4, // 4: types.EnsAddressChanged.time:type_name -> google.protobuf.Timestamp
	4, // 5: types.EnsNameChanged.time:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ens_proto_init() }
func file_ens_proto_init() {
	if File_ens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ens_proto_rawDesc), len(file_ens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ens_proto_goTypes,
		DependencyIndexes: file_ens_proto_depIdxs,
		MessageInfos:      file_ens_proto_msgTypes,
	}.Build()
	File_ens_proto = out.File
	file_ens_proto_goTypes = nil
	file_ens_proto_depIdxs = nil
}
