// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: machine.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineMetricSystem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExporterVersion string                 `protobuf:"bytes,2,opt,name=exporter_version,json=exporterVersion,proto3" json:"exporter_version,omitempty"`
	// system
	CpuCores                      uint64 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThreads                    uint64 `protobuf:"varint,4,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`
	CpuNodeSystemSecondsTotal     uint64 `protobuf:"varint,5,opt,name=cpu_node_system_seconds_total,json=cpuNodeSystemSecondsTotal,proto3" json:"cpu_node_system_seconds_total,omitempty"`
	CpuNodeUserSecondsTotal       uint64 `protobuf:"varint,6,opt,name=cpu_node_user_seconds_total,json=cpuNodeUserSecondsTotal,proto3" json:"cpu_node_user_seconds_total,omitempty"`
	CpuNodeIowaitSecondsTotal     uint64 `protobuf:"varint,7,opt,name=cpu_node_iowait_seconds_total,json=cpuNodeIowaitSecondsTotal,proto3" json:"cpu_node_iowait_seconds_total,omitempty"`
	CpuNodeIdleSecondsTotal       uint64 `protobuf:"varint,8,opt,name=cpu_node_idle_seconds_total,json=cpuNodeIdleSecondsTotal,proto3" json:"cpu_node_idle_seconds_total,omitempty"`
	MemoryNodeBytesTotal          uint64 `protobuf:"varint,9,opt,name=memory_node_bytes_total,json=memoryNodeBytesTotal,proto3" json:"memory_node_bytes_total,omitempty"`
	MemoryNodeBytesFree           uint64 `protobuf:"varint,10,opt,name=memory_node_bytes_free,json=memoryNodeBytesFree,proto3" json:"memory_node_bytes_free,omitempty"`
	MemoryNodeBytesCached         uint64 `protobuf:"varint,11,opt,name=memory_node_bytes_cached,json=memoryNodeBytesCached,proto3" json:"memory_node_bytes_cached,omitempty"`
	MemoryNodeBytesBuffers        uint64 `protobuf:"varint,12,opt,name=memory_node_bytes_buffers,json=memoryNodeBytesBuffers,proto3" json:"memory_node_bytes_buffers,omitempty"`
	DiskNodeBytesTotal            uint64 `protobuf:"varint,13,opt,name=disk_node_bytes_total,json=diskNodeBytesTotal,proto3" json:"disk_node_bytes_total,omitempty"`
	DiskNodeBytesFree             uint64 `protobuf:"varint,14,opt,name=disk_node_bytes_free,json=diskNodeBytesFree,proto3" json:"disk_node_bytes_free,omitempty"`
	DiskNodeIoSeconds             uint64 `protobuf:"varint,15,opt,name=disk_node_io_seconds,json=diskNodeIoSeconds,proto3" json:"disk_node_io_seconds,omitempty"`
	DiskNodeReadsTotal            uint64 `protobuf:"varint,16,opt,name=disk_node_reads_total,json=diskNodeReadsTotal,proto3" json:"disk_node_reads_total,omitempty"`
	DiskNodeWritesTotal           uint64 `protobuf:"varint,17,opt,name=disk_node_writes_total,json=diskNodeWritesTotal,proto3" json:"disk_node_writes_total,omitempty"`
	NetworkNodeBytesTotalReceive  uint64 `protobuf:"varint,18,opt,name=network_node_bytes_total_receive,json=networkNodeBytesTotalReceive,proto3" json:"network_node_bytes_total_receive,omitempty"`
	NetworkNodeBytesTotalTransmit uint64 `protobuf:"varint,19,opt,name=network_node_bytes_total_transmit,json=networkNodeBytesTotalTransmit,proto3" json:"network_node_bytes_total_transmit,omitempty"`
	MiscNodeBootTsSeconds         uint64 `protobuf:"varint,20,opt,name=misc_node_boot_ts_seconds,json=miscNodeBootTsSeconds,proto3" json:"misc_node_boot_ts_seconds,omitempty"`
	MiscOs                        string `protobuf:"bytes,21,opt,name=misc_os,json=miscOs,proto3" json:"misc_os,omitempty"`
	// do not store in bigtable but include them in generated model
	Machine       *string `protobuf:"bytes,22,opt,name=machine,proto3,oneof" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineMetricSystem) Reset() {
	*x = MachineMetricSystem{}
	mi := &file_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineMetricSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineMetricSystem) ProtoMessage() {}

func (x *MachineMetricSystem) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineMetricSystem.ProtoReflect.Descriptor instead.
func (*MachineMetricSystem) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineMetricSystem) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MachineMetricSystem) GetExporterVersion() string {
	if x != nil {
		return x.ExporterVersion
	}
	return ""
}

func (x *MachineMetricSystem) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *MachineMetricSystem) GetCpuThreads() uint64 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *MachineMetricSystem) GetCpuNodeSystemSecondsTotal() uint64 {
	if x != nil {
		return x.CpuNodeSystemSecondsTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetCpuNodeUserSecondsTotal() uint64 {
	if x != nil {
		return x.CpuNodeUserSecondsTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetCpuNodeIowaitSecondsTotal() uint64 {
	if x != nil {
		return x.CpuNodeIowaitSecondsTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetCpuNodeIdleSecondsTotal() uint64 {
	if x != nil {
		return x.CpuNodeIdleSecondsTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetMemoryNodeBytesTotal() uint64 {
	if x != nil {
		return x.MemoryNodeBytesTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetMemoryNodeBytesFree() uint64 {
	if x != nil {
		return x.MemoryNodeBytesFree
	}
	return 0
}

func (x *MachineMetricSystem) GetMemoryNodeBytesCached() uint64 {
	if x != nil {
		return x.MemoryNodeBytesCached
	}
	return 0
}

func (x *MachineMetricSystem) GetMemoryNodeBytesBuffers() uint64 {
	if x != nil {
		return x.MemoryNodeBytesBuffers
	}
	return 0
}

func (x *MachineMetricSystem) GetDiskNodeBytesTotal() uint64 {
	if x != nil {
		return x.DiskNodeBytesTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetDiskNodeBytesFree() uint64 {
	if x != nil {
		return x.DiskNodeBytesFree
	}
	return 0
}

func (x *MachineMetricSystem) GetDiskNodeIoSeconds() uint64 {
	if x != nil {
		return x.DiskNodeIoSeconds
	}
	return 0
}

func (x *MachineMetricSystem) GetDiskNodeReadsTotal() uint64 {
	if x != nil {
		return x.DiskNodeReadsTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetDiskNodeWritesTotal() uint64 {
	if x != nil {
		return x.DiskNodeWritesTotal
	}
	return 0
}

func (x *MachineMetricSystem) GetNetworkNodeBytesTotalReceive() uint64 {
	if x != nil {
		return x.NetworkNodeBytesTotalReceive
	}
	return 0
}

func (x *MachineMetricSystem) GetNetworkNodeBytesTotalTransmit() uint64 {
	if x != nil {
		return x.NetworkNodeBytesTotalTransmit
	}
	return 0
}

func (x *MachineMetricSystem) GetMiscNodeBootTsSeconds() uint64 {
	if x != nil {
		return x.MiscNodeBootTsSeconds
	}
	return 0
}

func (x *MachineMetricSystem) GetMiscOs() string {
	if x != nil {
		return x.MiscOs
	}
	return ""
}

func (x *MachineMetricSystem) GetMachine() string {
	if x != nil && x.Machine != nil {
		return *x.Machine
	}
	return ""
}

type MachineMetricValidator struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExporterVersion string                 `protobuf:"bytes,2,opt,name=exporter_version,json=exporterVersion,proto3" json:"exporter_version,omitempty"`
	// process
	CpuProcessSecondsTotal     uint64 `protobuf:"varint,3,opt,name=cpu_process_seconds_total,json=cpuProcessSecondsTotal,proto3" json:"cpu_process_seconds_total,omitempty"`
	MemoryProcessBytes         uint64 `protobuf:"varint,4,opt,name=memory_process_bytes,json=memoryProcessBytes,proto3" json:"memory_process_bytes,omitempty"`
	ClientName                 string `protobuf:"bytes,5,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion              string `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientBuild                uint64 `protobuf:"varint,7,opt,name=client_build,json=clientBuild,proto3" json:"client_build,omitempty"`
	SyncEth2FallbackConfigured bool   `protobuf:"varint,8,opt,name=sync_eth2_fallback_configured,json=syncEth2FallbackConfigured,proto3" json:"sync_eth2_fallback_configured,omitempty"`
	SyncEth2FallbackConnected  bool   `protobuf:"varint,9,opt,name=sync_eth2_fallback_connected,json=syncEth2FallbackConnected,proto3" json:"sync_eth2_fallback_connected,omitempty"`
	// validator
	ValidatorTotal  uint64 `protobuf:"varint,10,opt,name=validator_total,json=validatorTotal,proto3" json:"validator_total,omitempty"`
	ValidatorActive uint64 `protobuf:"varint,11,opt,name=validator_active,json=validatorActive,proto3" json:"validator_active,omitempty"`
	// do not store in bigtable but include them in generated model
	Machine       *string `protobuf:"bytes,12,opt,name=machine,proto3,oneof" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineMetricValidator) Reset() {
	*x = MachineMetricValidator{}
	mi := &file_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineMetricValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineMetricValidator) ProtoMessage() {}

func (x *MachineMetricValidator) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineMetricValidator.ProtoReflect.Descriptor instead.
func (*MachineMetricValidator) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{1}
}

func (x *MachineMetricValidator) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MachineMetricValidator) GetExporterVersion() string {
	if x != nil {
		return x.ExporterVersion
	}
	return ""
}

func (x *MachineMetricValidator) GetCpuProcessSecondsTotal() uint64 {
	if x != nil {
		return x.CpuProcessSecondsTotal
	}
	return 0
}

func (x *MachineMetricValidator) GetMemoryProcessBytes() uint64 {
	if x != nil {
		return x.MemoryProcessBytes
	}
	return 0
}

func (x *MachineMetricValidator) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *MachineMetricValidator) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *MachineMetricValidator) GetClientBuild() uint64 {
	if x != nil {
		return x.ClientBuild
	}
	return 0
}

func (x *MachineMetricValidator) GetSyncEth2FallbackConfigured() bool {
	if x != nil {
		return x.SyncEth2FallbackConfigured
	}
	return false
}

func (x *MachineMetricValidator) GetSyncEth2FallbackConnected() bool {
	if x != nil {
		return x.SyncEth2FallbackConnected
	}
	return false
}

func (x *MachineMetricValidator) GetValidatorTotal() uint64 {
	if x != nil {
		return x.ValidatorTotal
	}
	return 0
}

func (x *MachineMetricValidator) GetValidatorActive() uint64 {
	if x != nil {
		return x.ValidatorActive
	}
	return 0
}

func (x *MachineMetricValidator) GetMachine() string {
	if x != nil && x.Machine != nil {
		return *x.Machine
	}
	return ""
}

type MachineMetricNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExporterVersion string                 `protobuf:"bytes,2,opt,name=exporter_version,json=exporterVersion,proto3" json:"exporter_version,omitempty"`
	// process
	CpuProcessSecondsTotal     uint64 `protobuf:"varint,3,opt,name=cpu_process_seconds_total,json=cpuProcessSecondsTotal,proto3" json:"cpu_process_seconds_total,omitempty"`
	MemoryProcessBytes         uint64 `protobuf:"varint,4,opt,name=memory_process_bytes,json=memoryProcessBytes,proto3" json:"memory_process_bytes,omitempty"`
	ClientName                 string `protobuf:"bytes,5,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion              string `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientBuild                uint64 `protobuf:"varint,7,opt,name=client_build,json=clientBuild,proto3" json:"client_build,omitempty"`
	SyncEth2FallbackConfigured bool   `protobuf:"varint,8,opt,name=sync_eth2_fallback_configured,json=syncEth2FallbackConfigured,proto3" json:"sync_eth2_fallback_configured,omitempty"`
	SyncEth2FallbackConnected  bool   `protobuf:"varint,9,opt,name=sync_eth2_fallback_connected,json=syncEth2FallbackConnected,proto3" json:"sync_eth2_fallback_connected,omitempty"`
	// node
	DiskBeaconchainBytesTotal       uint64 `protobuf:"varint,10,opt,name=disk_beaconchain_bytes_total,json=diskBeaconchainBytesTotal,proto3" json:"disk_beaconchain_bytes_total,omitempty"`
	NetworkLibp2PBytesTotalReceive  uint64 `protobuf:"varint,11,opt,name=network_libp2p_bytes_total_receive,json=networkLibp2pBytesTotalReceive,proto3" json:"network_libp2p_bytes_total_receive,omitempty"`
	NetworkLibp2PBytesTotalTransmit uint64 `protobuf:"varint,12,opt,name=network_libp2p_bytes_total_transmit,json=networkLibp2pBytesTotalTransmit,proto3" json:"network_libp2p_bytes_total_transmit,omitempty"`
	NetworkPeersConnected           uint64 `protobuf:"varint,13,opt,name=network_peers_connected,json=networkPeersConnected,proto3" json:"network_peers_connected,omitempty"`
	SyncEth1Connected               bool   `protobuf:"varint,14,opt,name=sync_eth1_connected,json=syncEth1Connected,proto3" json:"sync_eth1_connected,omitempty"`
	SyncEth2Synced                  bool   `protobuf:"varint,15,opt,name=sync_eth2_synced,json=syncEth2Synced,proto3" json:"sync_eth2_synced,omitempty"`
	SyncBeaconHeadSlot              uint64 `protobuf:"varint,16,opt,name=sync_beacon_head_slot,json=syncBeaconHeadSlot,proto3" json:"sync_beacon_head_slot,omitempty"`
	SyncEth1FallbackConfigured      bool   `protobuf:"varint,17,opt,name=sync_eth1_fallback_configured,json=syncEth1FallbackConfigured,proto3" json:"sync_eth1_fallback_configured,omitempty"`
	SyncEth1FallbackConnected       bool   `protobuf:"varint,18,opt,name=sync_eth1_fallback_connected,json=syncEth1FallbackConnected,proto3" json:"sync_eth1_fallback_connected,omitempty"`
	// do not store in bigtable but include them in generated model
	Machine       *string `protobuf:"bytes,19,opt,name=machine,proto3,oneof" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineMetricNode) Reset() {
	*x = MachineMetricNode{}
	mi := &file_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineMetricNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineMetricNode) ProtoMessage() {}

func (x *MachineMetricNode) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineMetricNode.ProtoReflect.Descriptor instead.
func (*MachineMetricNode) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineMetricNode) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MachineMetricNode) GetExporterVersion() string {
	if x != nil {
		return x.ExporterVersion
	}
	return ""
}

func (x *MachineMetricNode) GetCpuProcessSecondsTotal() uint64 {
	if x != nil {
		return x.CpuProcessSecondsTotal
	}
	return 0
}

func (x *MachineMetricNode) GetMemoryProcessBytes() uint64 {
	if x != nil {
		return x.MemoryProcessBytes
	}
	return 0
}

func (x *MachineMetricNode) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *MachineMetricNode) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *MachineMetricNode) GetClientBuild() uint64 {
	if x != nil {
		return x.ClientBuild
	}
	return 0
}

func (x *MachineMetricNode) GetSyncEth2FallbackConfigured() bool {
	if x != nil {
		return x.SyncEth2FallbackConfigured
	}
	return false
}

func (x *MachineMetricNode) GetSyncEth2FallbackConnected() bool {
	if x != nil {
		return x.SyncEth2FallbackConnected
	}
	return false
}

func (x *MachineMetricNode) GetDiskBeaconchainBytesTotal() uint64 {
	if x != nil {
		return x.DiskBeaconchainBytesTotal
	}
	return 0
}

func (x *MachineMetricNode) GetNetworkLibp2PBytesTotalReceive() uint64 {
	if x != nil {
		return x.NetworkLibp2PBytesTotalReceive
	}
	return 0
}

func (x *MachineMetricNode) GetNetworkLibp2PBytesTotalTransmit() uint64 {
	if x != nil {
		return x.NetworkLibp2PBytesTotalTransmit
	}
	return 0
}

func (x *MachineMetricNode) GetNetworkPeersConnected() uint64 {
	if x != nil {
		return x.NetworkPeersConnected
	}
	return 0
}

func (x *MachineMetricNode) GetSyncEth1Connected() bool {
	if x != nil {
		return x.SyncEth1Connected
	}
	return false
}

func (x *MachineMetricNode) GetSyncEth2Synced() bool {
	if x != nil {
		return x.SyncEth2Synced
	}
	return false
}

func (x *MachineMetricNode) GetSyncBeaconHeadSlot() uint64 {
	if x != nil {
		return x.SyncBeaconHeadSlot
	}
	return 0
}

func (x *MachineMetricNode) GetSyncEth1FallbackConfigured() bool {
	if x != nil {
		return x.SyncEth1FallbackConfigured
	}
	return false
}

func (x *MachineMetricNode) GetSyncEth1FallbackConnected() bool {
	if x != nil {
		return x.SyncEth1FallbackConnected
	}
	return false
}

func (x *MachineMetricNode) GetMachine() string {
	if x != nil && x.Machine != nil {
		return *x.Machine
	}
	return ""
}

var File_machine_proto protoreflect.FileDescriptor

const file_machine_proto_rawDesc = "" +
	"\n" +
	"\rmachine.proto\x12\x05types\"\x89\t\n" +
	"\x13MachineMetricSystem\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12)\n" +
	"\x10exporter_version\x18\x02 \x01(\tR\x0fexporterVersion\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x04R\bcpuCores\x12\x1f\n" +
	"\vcpu_threads\x18\x04 \x01(\x04R\n" +
	"cpuThreads\x12@\n" +
	"\x1dcpu_node_system_seconds_total\x18\x05 \x01(\x04R\x19cpuNodeSystemSecondsTotal\x12<\n" +
	"\x1bcpu_node_user_seconds_total\x18\x06 \x01(\x04R\x17cpuNodeUserSecondsTotal\x12@\n" +
	"\x1dcpu_node_iowait_seconds_total\x18\a \x01(\x04R\x19cpuNodeIowaitSecondsTotal\x12<\n" +
	"\x1bcpu_node_idle_seconds_total\x18\b \x01(\x04R\x17cpuNodeIdleSecondsTotal\x125\n" +
	"\x17memory_node_bytes_total\x18\t \x01(\x04R\x14memoryNodeBytesTotal\x123\n" +
	"\x16memory_node_bytes_free\x18\n" +
	" \x01(\x04R\x13memoryNodeBytesFree\x127\n" +
	"\x18memory_node_bytes_cached\x18\v \x01(\x04R\x15memoryNodeBytesCached\x129\n" +
	"\x19memory_node_bytes_buffers\x18\f \x01(\x04R\x16memoryNodeBytesBuffers\x121\n" +
	"\x15disk_node_bytes_total\x18\r \x01(\x04R\x12diskNodeBytesTotal\x12/\n" +
	"\x14disk_node_bytes_free\x18\x0e \x01(\x04R\x11diskNodeBytesFree\x12/\n" +
	"\x14disk_node_io_seconds\x18\x0f \x01(\x04R\x11diskNodeIoSeconds\x121\n" +
	"\x15disk_node_reads_total\x18\x10 \x01(\x04R\x12diskNodeReadsTotal\x123\n" +
	"\x16disk_node_writes_total\x18\x11 \x01(\x04R\x13diskNodeWritesTotal\x12F\n" +
	" network_node_bytes_total_receive\x18\x12 \x01(\x04R\x1cnetworkNodeBytesTotalReceive\x12H\n" +
	"!network_node_bytes_total_transmit\x18\x13 \x01(\x04R\x1dnetworkNodeBytesTotalTransmit\x128\n" +
	"\x19misc_node_boot_ts_seconds\x18\x14 \x01(\x04R\x15miscNodeBootTsSeconds\x12\x17\n" +
	"\amisc_os\x18\x15 \x01(\tR\x06miscOs\x12\x1d\n" +
	"\amachine\x18\x16 \x01(\tH\x00R\amachine\x88\x01\x01B\n" +
	"\n" +
	"\b_machine\"\xbc\x04\n" +
	"\x16MachineMetricValidator\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12)\n" +
	"\x10exporter_version\x18\x02 \x01(\tR\x0fexporterVersion\x129\n" +
	"\x19cpu_process_seconds_total\x18\x03 \x01(\x04R\x16cpuProcessSecondsTotal\x120\n" +
	"\x14memory_process_bytes\x18\x04 \x01(\x04R\x12memoryProcessBytes\x12\x1f\n" +
	"\vclient_name\x18\x05 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x06 \x01(\tR\rclientVersion\x12!\n" +
	"\fclient_build\x18\a \x01(\x04R\vclientBuild\x12A\n" +
	"\x1dsync_eth2_fallback_configured\x18\b \x01(\bR\x1asyncEth2FallbackConfigured\x12?\n" +
	"\x1csync_eth2_fallback_connected\x18\t \x01(\bR\x19syncEth2FallbackConnected\x12'\n" +
	"\x0fvalidator_total\x18\n" +
	" \x01(\x04R\x0evalidatorTotal\x12)\n" +
	"\x10validator_active\x18\v \x01(\x04R\x0fvalidatorActive\x12\x1d\n" +
	"\amachine\x18\f \x01(\tH\x00R\amachine\x88\x01\x01B\n" +
	"\n" +
	"\b_machine\"\x87\b\n" +
	"\x11MachineMetricNode\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12)\n" +
	"\x10exporter_version\x18\x02 \x01(\tR\x0fexporterVersion\x129\n" +
	"\x19cpu_process_seconds_total\x18\x03 \x01(\x04R\x16cpuProcessSecondsTotal\x120\n" +
	"\x14memory_process_bytes\x18\x04 \x01(\x04R\x12memoryProcessBytes\x12\x1f\n" +
	"\vclient_name\x18\x05 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x06 \x01(\tR\rclientVersion\x12!\n" +
	"\fclient_build\x18\a \x01(\x04R\vclientBuild\x12A\n" +
	"\x1dsync_eth2_fallback_configured\x18\b \x01(\bR\x1asyncEth2FallbackConfigured\x12?\n" +
	"\x1csync_eth2_fallback_connected\x18\t \x01(\bR\x19syncEth2FallbackConnected\x12?\n" +
	"\x1cdisk_beaconchain_bytes_total\x18\n" +
	" \x01(\x04R\x19diskBeaconchainBytesTotal\x12J\n" +
	"\"network_libp2p_bytes_total_receive\x18\v \x01(\x04R\x1enetworkLibp2pBytesTotalReceive\x12L\n" +
	"#network_libp2p_bytes_total_transmit\x18\f \x01(\x04R\x1fnetworkLibp2pBytesTotalTransmit\x126\n" +
	"\x17network_peers_connected\x18\r \x01(\x04R\x15networkPeersConnected\x12.\n" +
	"\x13sync_eth1_connected\x18\x0e \x01(\bR\x11syncEth1Connected\x12(\n" +
	"\x10sync_eth2_synced\x18\x0f \x01(\bR\x0esyncEth2Synced\x121\n" +
	"\x15sync_beacon_head_slot\x18\x10 \x01(\x04R\x12syncBeaconHeadSlot\x12A\n" +
	"\x1dsync_eth1_fallback_configured\x18\x11 \x01(\bR\x1asyncEth1FallbackConfigured\x12?\n" +
	"\x1csync_eth1_fallback_connected\x18\x12 \x01(\bR\x19syncEth1FallbackConnected\x12\x1d\n" +
	"\amachine\x18\x13 \x01(\tH\x00R\amachine\x88\x01\x01B\n" +
	"\n" +
	"\b_machineB\tZ\a./typesb\x06proto3"

var (
	file_machine_proto_rawDescOnce sync.Once
	file_machine_proto_rawDescData []byte
)

func file_machine_proto_rawDescGZIP() []byte {
	file_machine_proto_rawDescOnce.Do(func() {
		file_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machine_proto_rawDesc), len(file_machine_proto_rawDesc)))
	})
	return file_machine_proto_rawDescData
}

var file_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_machine_proto_goTypes = []any{
	(*MachineMetricSystem)(nil),    // 0: types.MachineMetricSystem
	(*MachineMetricValidator)(nil), // 1: types.MachineMetricValidator
	(*MachineMetricNode)(nil),      // 2: types.MachineMetricNode
}
var file_machine_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_machine_proto_init() }
func file_machine_proto_init() {
	if File_machine_proto != nil {
		return
	}
	file_machine_proto_msgTypes[0].OneofWrappers = []any{}
	file_machine_proto_msgTypes[1].OneofWrappers = []any{}
	file_machine_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machine_proto_rawDesc), len(file_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machine_proto_goTypes,
		DependencyIndexes: file_machine_proto_depIdxs,
		MessageInfos:      file_machine_proto_msgTypes,
	}.Build()
	File_machine_proto = out.File
	file_machine_proto_goTypes = nil
	file_machine_proto_depIdxs = nil
}
