# Extends the mainnet preset
PRESET_BASE: 'mainnet'
CONFIG_NAME: testnet # needs to exist because of Prysm. Otherwise it conflicts with mainnet genesis

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 58000
# Feb-01-2023 15:00:00 PM UTC
# This is an invalid valid and should be updated when you create the genesis
MIN_GENESIS_TIME: 1675263480
GENESIS_FORK_VERSION: 0x00000069
GENESIS_DELAY: 120


# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x00000070
ALTAIR_FORK_EPOCH: 0
# Merge
BELLATRIX_FORK_VERSION: 0x00000071
BELLATRIX_FORK_EPOCH: 0
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Capella
CAPELLA_FORK_VERSION: 0x00000072
CAPELLA_FORK_EPOCH: 1350

# EIP4844
EIP4844_FORK_VERSION: 0x00000073
EIP4844_FORK_EPOCH: 18446744073709551615

# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 12
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 12


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 1337803
DEPOSIT_NETWORK_ID: 1337803
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648
MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 64
PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2
SYNC_COMMITTEE_SIZE: 512
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256
MIN_SYNC_COMMITTEE_PARTICIPANTS: 1
UPDATE_TIMEOUT: 8192
INACTIVITY_PENALTY_QUOTIENT_BELLATRIX: 16777216
MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX: 32
PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX: 3
MAX_BYTES_PER_TRANSACTION: 1073741824
MAX_TRANSACTIONS_PER_PAYLOAD: 1048576
BYTES_PER_LOGS_BLOOM: 256
MAX_EXTRA_DATA_BYTES: 32
RANDAO_PENALTY_EPOCHS: 2
EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS: 32768
EPOCHS_PER_CUSTODY_PERIOD: 16384
CUSTODY_PERIOD_TO_RANDAO_PADDING: 2048
MAX_CHUNK_CHALLENGE_DELAY: 32768
MAX_CUSTODY_KEY_REVEALS: 256
MAX_EARLY_DERIVED_SECRET_REVEALS: 1
MAX_CUSTODY_CHUNK_CHALLENGES: 4
MAX_CUSTODY_CHUNK_CHALLENGE_RESP: 16
MAX_CUSTODY_SLASHINGS: 1
EARLY_DERIVED_SECRET_REVEAL_SLOT_REWARD_MULTIPLE: 2
MINOR_REWARD_QUOTIENT: 256
MAX_COMMITTEES_PER_SLOT: 64
TARGET_COMMITTEE_SIZE: 128
MAX_VALIDATORS_PER_COMMITTEE: 2048
SHUFFLE_ROUND_COUNT: 90
HYSTERESIS_QUOTIENT: 4
SLOTS_PER_EPOCH: 32
MAX_EFFECTIVE_BALANCE: 32000000000



# Minimal preset - Capella

# Max operations per block
# ---------------------------------------------------------------
# 2**4 (= 16)
MAX_BLS_TO_EXECUTION_CHANGES: 16


# Execution
# ---------------------------------------------------------------
# [customized] 2**2 (= 4)
MAX_WITHDRAWALS_PER_PAYLOAD: 4

# Withdrawals processing
# ---------------------------------------------------------------
# [customized] 2**4 (= 16) validators
MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP: 16