get:
  tags:
    - User
  summary: Device settings
  description: >-
    Get your device settings, currently only whether to enable mobile
    notifcations or not
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/types.ApiResponse.yaml
              - properties:
                  data:
                    $ref: ../components/schemas/types.MobileSettingsData.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/types.ApiErrorResponse.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/types.ApiErrorResponse.yaml
post:
  tags:
    - User
  summary: Update device settings
  description: >-
    Update your device settings, currently only whether to enable mobile
    notifcations or not.
  requestBody:
    description: Whether to enable mobile notifications for this device or not
    content:
      application/json:
        schema: {}
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/types.ApiResponse.yaml
              - properties:
                  data:
                    $ref: ../components/schemas/types.MobileSettingsData.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/types.ApiErrorResponse.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/types.ApiErrorResponse.yaml
