<template>
  <div class="hero-container">
    <div class="hero-image">
      <div id="hero-feed" class="d-none shadow-sm">
        <ul class="d-flex flex-column align-items-center"></ul>
        <span class="donate-btn"><img src="/img/gitcoin_logo.svg" style="width: auto; height: 30px" /></span>
      </div>
      <!--<template v-if="indexData.Countdown.Enabled">
        <div class="countdown fade-in-top d-none d-lg-block">
          <h1 class="countdown-headline" style="margin-bottom: 15px; font-size: 42px; font-weight: 900; letter-spacing: 2px; color: #343a40;">{{ indexData.Countdown.Title }}</h1>
          <div class="d-flex justify-content-between">
            <div>
              <div class="d-flex align-items-center justify-content-between mr-3 mb-1">
                <h2 class="countdown-epoch" style="font-size: 28px; font-weight: 700; letter-spacing: 3px; color: #343a40; text-align: left;"></h2>
                <h2 class="countdown-slot" style="font-size: 28px; font-weight: 700; letter-spacing: 3px; color: #343a40; text-align: right;"></h2>
              </div>
              <h2 class="countdown-time" style="font-size: 28px; font-weight: 700; letter-spacing: 3px; color: #343a40;"></h2>
              <span style="color: #343a40;">{{ indexData.Countdown.info }}</span>
            </div>
            <i class="fas fa-hourglass-half fa-7x mt-3 rotated-icon" style="color: #565876;"></i>
          </div>
        </div>
      </template>
      -->
      <heroSVG></heroSVG>
    </div>
    <div class="hero-text">
      <div class="hero-text-background"></div>
      <h1 class="mt-4 text-center">{{ indexData.title }}</h1>
      <h5 class="text-center">{{ indexData.subtitle }}</h5>
      <h6 class="text-center">
        <!-- <a href="https://gitter.im/gobitfly/beaconchain-explorer"><i class="fab fa-gitter"></i> Gitter</a> | -->
        <router-link to="/mobile"><i class="fas fa-mobile-alt mr-2"></i>Mobile App</router-link> | <router-link to="/premium"><i class="mr-1 mb-1 fas fa-user-astronaut mr-2" height="16"></i>Premium</router-link> |
        <router-link to="/advertisewithus" class="my-1"><i class="fas fa-ad mr-2"></i>Advertise</router-link>
      </h6>
    </div>
    <!--
    <template v-if="indexData.Countdown.Enabled">
      <div class="d-flex d-lg-none align-items-center justify-content-center w-100 mt-2">
        <div class="d-flex flex-column" style="position: relative; top: 0;">
          <h1 class="countdown-headline" style="font-size: 24px; font-weight: 700; letter-spacing: 2px; color: #343a40;">{{ indexData.Countdown.Title }}</h1>
          <h2 class="countdown-time" style="font-size: 18px; font-weight: 700; letter-spacing: 3px; color: #343a40;"></h2>
        </div>
      </div>
    </template>
    -->
  </div>
</template>

<script setup>
import { onServerPrefetch, onMounted, computed } from "vue"
import { useState } from "@/stores/state.js"

import heroSVG from "#/static/img/hero.svg"

const state = useState()

const indexData = computed(() => state.indexData)
</script>

<style scoped>
.hero-container {
  position: relative;
  min-height: 250px;
  width: 100%;
  display: flex;
  flex-direction: row-reverse;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  margin-bottom: 1rem;
  margin-top: 1rem;
}

.hero-image {
  overflow: hidden;
  flex: 1;
  max-width: 500px;
  min-width: 320px;
  max-height: 400px;
  min-height: 200px;
  position: relative;
}

.hero-image svg {
  overflow: hidden;
  width: inherit;
  height: inherit;
}

.hero-text {
  font-size: 2rem;
  flex: 1;
  min-width: 305px;
  max-width: 500px;
  position: relative;
}

.hero-text-background {
  position: absolute;
  width: 100%;
  height: 98%;
  /* bottom: -40%; */
  /* transform: scale(.5) translateY(20%); */
  border-radius: 65% 35% 70% 30% / 50% 50% 50% 50%;
  background-image: var(--linear-gradient);
  box-shadow: 5px 15px 30px var(--shadow-light);
  z-index: -50;
  -webkit-animation: slide-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  opacity: 0.6;
}

/* ----------------------------------------------
             * Generated by Animista on 2020-5-27 13:15:6
             * Licensed under FreeBSD License.
             * See http://animista.net/license for more info.
             * w: http://animista.net, t: @cssanimista
             * ---------------------------------------------- */
@-webkit-keyframes slide-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }

  100% {
    -webkit-transform: scale(1) translateY(25%);
    transform: scale(1) translateY(25%);
  }
}

@keyframes slide-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }

  100% {
    -webkit-transform: scale(1) translateY(25%);
    transform: scale(1) translateY(25%);
  }
}

@media (max-width: 1140px) {
  .hero-text-background {
    animation: none;
    transform: scale(1) translateY(1.5rem);
    height: calc(100% - 1.5rem);
    border-radius: 0.5rem;
    opacity: 0.8;
  }

  .hero-container {
    margin-bottom: 50px;
  }
}

@media (max-width: 960px) {
  .hero-image {
    position: absolute;
    width: 100%;
    height: 100%;
  }

  .hero-container {
    flex-wrap: nowrap;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .hero-text {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
  }

  .hero-image svg {
    opacity: 0.2;
  }

  .hero-text-background {
    transform: scale(1) translateY(10%);
    animation: none;
    opacity: 0.1;
  }
}
</style>
