name: Publish Docker dencun-devnet-8 images

on:
  # Trigger the workflow on push or pull request,
  # but only for the dencun-devnet-8 branch
  push:
    branches:
      - dencun-devnet-8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Dockerhub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gobitfly/eth2-beaconchain-explorer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "dencun-devnet-8"
